Repository mongodb/helm-charts, pull requests merged in 2022-02, with the labels that each got.

#98 Enterprise-operator: Added chart's values to support nodeSelector, tolerations and affinity
  charts/enterprise-operator/templates/operator.yaml
  charts/enterprise-operator/values-openshift.yaml
  charts/enterprise-operator/values.yaml
Labels: CLOUDP-112335

#102 Fixed operator's role bindings to be bond correctly
  charts/community-operator/templates/operator_roles.yaml
Labels: CLOUDP-112334

#111 [atlas-operator]: metrics listen :8080
  charts/atlas-operator/templates/deployment.yaml
Labels: CLOUDP-112333
